[toolchain]
anchor_version = "0.31.0"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
unitas_oracle = "UtydtkrzVyT4UDNVp2zoEycyaonoQCKHRKa4wMyEJrw"

[programs.mainnet]
unitas_oracle = "UtydtkrzVyT4UDNVp2zoEycyaonoQCKHRKa4wMyEJrw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
add-account = "yarn run ts-node app/add-account.ts"
add-operator = "yarn run ts-node app/add-operator.ts"
create-asset-lookup-table = "yarn run ts-node app/create-asset-lookup-table.ts"
init-config = "yarn run ts-node app/init-config.ts"
remove-account = "yarn run ts-node app/remove-account.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
